# Meta Data for SEO

## Homepage
title = "Statusflare Docs"
titleSeparator = "-"
titleAddition = "Monitoring Made Easy."
description = "The authoritative documentation site for Statusflare."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "statusflare_com"
twitterCreator = "statusflare_com"
facebookAuthor = "statusflare_com"
facebookPublisher = "statusflare_com"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/statusflare_com"
schemaLinkedIn = "https://www.linkedin.com/"
schemaGitHub = "https://github.com/statusflare-com"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://pages.cloudflare.com\">Cloudflare Pages</a>. Join our <a href=\"https://discord.gg/psfJKMCN4v">Discord Server</a>."

# Alert
alert = false
alertText = "Like Statusflare? <a class=\"alert-link\" href=\"https://www.statusflare.com\">See our website!</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com"
editPage = false

[options]
  lazySizes = true
  clipBoard = false
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
